import { Inter } from "next/font/google";
import "./globals.css";
import { Authentication } from "./components/Authentication";
import ReactQueryProvider from "./util/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DFLIX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Authentication />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
