import { Inter } from 'next/font/google';
import './globals.css';
import RQProvider from './components/RQProvider';
import Nav from './components/Nav';

export const metadata = {
	title: 'DFLIX',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="ko">
			<body className="flex flex-col w-screen overflow-x-hidden">
				<RQProvider>
					<div>
						<Nav />
					</div>
					<div>{children}</div>
				</RQProvider>
			</body>
		</html>
	);
}
